# Generated by Django 3.2.16 on 2023-05-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default='description', max_length=600),
        ),
    ]
