# Generated by Django 3.2.16 on 2023-10-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(default='link', max_length=100),
        ),
    ]
